apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
     name: redis-service
     app: myapp-pod
spec:
##clusterIP by default
  selector:
     name: redis-pod
     app: myapp-pod  
  ports:
  ##port of redis 
    - port: 6379
      targetPort: 6379
